FROM nginx:alpine

RUN rm -f /etc/nginx/conf.d/default.conf

COPY docs/nginx.conf /etc/nginx/conf.d/default.conf

COPY cheatsheets/ /usr/share/nginx/html/

RUN chmod -R a+r /usr/share/nginx/html

EXPOSE 80
